name: Playwright Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests in headless-mode
        run: npx playwright test --reporter=html,json 2>&1 | tee playwright-output.log

      - name: Extract Test Statistics from JSON logs
        run: |
          TOTAL=$(jq '.stats.expected' playwright-output.log || echo "0")
          FAILED=$(jq '.stats.unexpected' playwright-output.log || echo "0")
          PASSED=$((TOTAL - FAILED))
          if [ "$PASSED" -lt 0 ]; then PASSED=0; fi

          echo "TOTAL_TESTS=$TOTAL" >> $GITHUB_ENV
          echo "PASSED_TESTS=$PASSED" >> $GITHUB_ENV
          echo "FAILED_TESTS=$FAILED" >> $GITHUB_ENV

          echo "📊 Статистика тестів:"
          echo "🔢 Загальна кількість: $TOTAL"
          echo "✅ Пройдені: $PASSED"
          echo "❌ Провалені: $FAILED"

      - name: Comment on PR with test results
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            📊 **Результати тестування**
            🔢 Загальна кількість тестів: **${{ env.TOTAL_TESTS }}**
            ✅ Виконано тестів: **${{ env.PASSED_TESTS }}**
            ❌ Завалено тестів: **${{ env.FAILED_TESTS }}**
            🔗 [Переглянути HTML-звіт](./playwright-report/index.html)
          repo-token: ${{ secrets.GITHUB_TOKEN }}