name: Run Tests on PR

on:
  pull_request: 
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests in headless-mode
        run: npx playwright test --reporter=html --output=test-results/

      - name: Debug test results (перевірка наявності файлів)
        run: ls -la test-results/html-report || echo "WARNING: HTML-report not found!"

      - name: Save HTML Report
        if: always()  # Завжди зберігаємо звіт, навіть якщо тести пройшли
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: test-results/html-report/
  
  comment:
    needs: test  # Виконується після тестів
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download HTML Report
        uses: actions/download-artifact@v4
        with:
          name: html-report
          path: test-results/html-report/

      - name: Publish comment with link to report
        uses: mshick/add-pr-comment@v2
        with:
          message: "📊 Тестовий звіт доступний [тут](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
