name: Run Tests on PR

on:
  pull_request:
    branches:
      - main  

permissions:
  contents: write  
  actions: write  
  pull-requests: write  

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Debug Playwright Config & Ensure JSON Report is Set
        run: |
          echo "📄 Перевіряємо Playwright config..."
          cat playwright.config.ts || echo "⚠️ WARNING: Файл playwright.config.ts не знайдено!"
          echo "🔍 Переконуємось, що Playwright записує JSON-звіт!"

      - name: Run tests in headless-mode
        run: npx playwright test --reporter=html,json

      - name: Debug Playwright Report Directory
        if: always()
        run: |
          echo "🔍 Перевіряємо, чи існує JSON-звіт..."
          ls -la playwright-report || echo "⚠️ WARNING: Папка playwright-report не знайдена!"
          if [ -f "playwright-report/test-results.json" ]; then
            echo "✅ JSON-звіт знайдено!"
            cat playwright-report/test-results.json | head -n 20  # Вивести перші 20 рядків JSON для перевірки
          else
            echo "❌ JSON-звіт НЕ створено!"
          fi

      - name: Save HTML Report (артефакт)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ github.event.pull_request.number }}
          path: playwright-report/
          retention-days: 7  

  comment:
    needs: test  
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Download HTML Report
        uses: actions/download-artifact@v4
        with:
          name: html-report-${{ github.event.pull_request.number }}
          path: playwright-report/

      - name: Count Passed/Failed Tests
        run: |
          TEST_RESULTS_FILE="playwright-report/test-results.json"
          if [ -f "$TEST_RESULTS_FILE" ]; then
            TOTAL=$(jq '[.suites[].specs[] | .tests | length] | add' $TEST_RESULTS_FILE)
            PASSED=$(jq '[.suites[].specs[].tests[] | select(.results[].status=="passed")] | length' $TEST_RESULTS_FILE)
            FAILED=$(jq '[.suites[].specs[].tests[] | select(.results[].status=="failed")] | length' $TEST_RESULTS_FILE)
            echo "✅ JSON-звіт знайдено! Дані:"
            echo "🔢 Загальна кількість тестів: $TOTAL"
            echo "✅ Пройдені тести: $PASSED"
            echo "❌ Провалені тести: $FAILED"
          else
            echo "❌ JSON-звіт НЕ знайдено! Використовуємо 0 значень."
            TOTAL=0
            PASSED=0
            FAILED=0
          fi
          echo "TOTAL_TESTS=$TOTAL" >> $GITHUB_ENV
          echo "PASSED_TESTS=$PASSED" >> $GITHUB_ENV
          echo "FAILED_TESTS=$FAILED" >> $GITHUB_ENV

      - name: Publish comment with test summary
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            📊 **Результати тестування**
            🔢 Загальна кількість тестів: `${{ env.TOTAL_TESTS }}`
            ✅ Виконано тестів: `${{ env.PASSED_TESTS }}`
            ❌ Завалено тестів: `${{ env.FAILED_TESTS }}`
            🔗 **[Переглянути HTML-звіт](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**
          repo-token: ${{ secrets.GITHUB_TOKEN }}
