name: Run Tests on PR

on:
  pull_request:
    branches:
      - main  

permissions:
  contents: write  # Потрібно для GitHub Pages
  actions: write
  pages: write  

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests in headless-mode
        run: npx playwright test

      - name: Debug test results (перевірка наявності файлів)
        if: always()
        run: |
          echo "🔍 Перевірка директорії playwright-report"
          ls -la playwright-report || echo "WARNING playwright-report не знайдено!"

      - name: Deploy HTML Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
          publish_branch: gh-pages  # Гілка для GitHub Pages

  comment:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Test Results
        run: |
          TEST_RESULTS=$(npx playwright show-report --output=playwright-report | grep '✓' | wc -l)
          FAILED_TESTS=$(npx playwright show-report --output=playwright-report | grep '✗' | wc -l)
          echo "TEST_RESULTS=$TEST_RESULTS" >> $GITHUB_ENV
          echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV

      - name: Publish comment with test summary
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            📊 **Результати тестування**
            ✅ Виконано тестів: ${{ env.TEST_RESULTS }}
            ❌ Завалено тестів: ${{ env.FAILED_TESTS }}
            🔗 **HTML-звіт:** [Переглянути тут](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
