name: Run Tests on PR

on:
  pull_request:  # Запуск тестів при створенні PR
    branches:
      - main  # Або інша гілка, в яку відправляється PR

jobs:
  test:
    runs-on: ubuntu-latest  # Виконання на Linux
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3

      - name: Встановлення Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Встановлення залежностей
      #   run: npm install

      - name: Встановлення Playwright
        run: npx playwright install --with-deps

      - name: Запуск тестів у headless-режимі
        run: npx playwright test

      - name: Збереження результатів тестування
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/  # Вказати папку для логів (змінюй за потреби)
