name: Run Tests on PR

on:
  pull_request: 
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests in headless-mode
        run: npx playwright test

      - name: Debug test results (перевірка наявності файлів)
        if: always()
        run: |
          echo "🔍 Перевірка директорії test-results"
          ls -la test-results || echo "WARNING test-results не знайдено!"
          
          echo "🔍 Перевірка директорії playwright-report"
          ls -la playwright-report || echo "WARNING playwright-report не знайдено!"

      - name: Save HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report/  # Виправлений шлях!

  comment:
    needs: test  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Виправлено помилку тут!

      - name: Download HTML Report
        uses: actions/download-artifact@v4
        with:
          name: html-report
          path: playwright-report/

      - name: Publish comment with link to report
        uses: mshick/add-pr-comment@v2
        with:
          message: "📊 Тестовий звіт доступний [тут](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
