name: Run Tests on PR

on:
  pull_request:
    branches:
      - main  

permissions:
  contents: write  
  actions: write  
  pull-requests: write  

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests in headless-mode
        run: npx playwright test --reporter=html,json

      - name: Debug test results
        if: always()
        run: |
          echo "🔍 Перевірка директорії playwright-report"
          ls -la playwright-report || echo "WARNING playwright-report не знайдено!"

      - name: Save HTML Report (артефакт)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ github.event.pull_request.number }}
          path: playwright-report/
          retention-days: 7  

  comment:
    needs: test  
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Download HTML Report
        uses: actions/download-artifact@v4
        with:
          name: html-report-${{ github.event.pull_request.number }}
          path: playwright-report/

      - name: Count Passed/Failed Tests
        run: |
          TEST_RESULTS_FILE="playwright-report/data/test-results.json"
          if [ -f "$TEST_RESULTS_FILE" ]; then
            PASSED=$(jq '[.suites[].specs[].tests[] | select(.results[].status=="passed")] | length' $TEST_RESULTS_FILE)
            FAILED=$(jq '[.suites[].specs[].tests[] | select(.results[].status=="failed")] | length' $TEST_RESULTS_FILE)
            TOTAL=$(jq '[.suites[].specs[].tests[]] | length' $TEST_RESULTS_FILE)
          else
            PASSED=0
            FAILED=0
            TOTAL=0
          fi
          echo "PASSED_TESTS=$PASSED" >> $GITHUB_ENV
          echo "FAILED_TESTS=$FAILED" >> $GITHUB_ENV
          echo "TOTAL_TESTS=$TOTAL" >> $GITHUB_ENV

      - name: Publish comment with test summary
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            📊 **Результати тестування**
            🔢 Загальна кількість тестів: `${{ env.TOTAL_TESTS }}`
            ✅ Виконано тестів: `${{ env.PASSED_TESTS }}`
            ❌ Завалено тестів: `${{ env.FAILED_TESTS }}`
            🔗 **[Переглянути HTML-звіт](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)**
          repo-token: ${{ secrets.GITHUB_TOKEN }}
